export const LOAD_COUNTRY_REQUEST = "LOAD_COUNTRY_REQUEST";
export const LOAD_COUNTRY_SUCCESS = "LOAD_COUNTRY_SUCCESS";
export const LOAD_COUNTRY_FAIL = "LOAD_COUNTRY_FAIL";

export const LOAD_DETAILS_REQUEST = "LOAD_DETAILS_REQUEST";
export const LOAD_DETAILS_SUCCESS = "LOAD_DETAILS_SUCCESS";
export const LOAD_DETAILS_FAIL = "LOAD_DETAILS_FAIL";

export const SEARCH_COUNTRY_REQUEST = "SEARCH_COUNTRY_REQUEST";
export const SEARCH_COUNTRY_SUCCESS = "SEARCH_COUNTRY_SUCCESS";
export const SEARCH_COUNTRY_FAIL = "SEARCH_COUNTRY_FAIL";

export const CLEAR_COUNTRY_DETAILS = "CLEAR_COUNTRY_DETAILS";

export const LOAD_BYREGION_REQUEST = "LOAD_BYREGION_REQUEST";
export const LOAD_BYREGION_SUCCESS = "LOAD_BYREGION_SUCCESS";
export const LOAD_BYREGION_FAIL = "LOAD_BYREGION_FAIL";

export const TOGGLE_THEME = "TOGGLE_THEME";
